services:
  worker:
    image: apache/airflow:3.2.0
    command: celery worker
    env_file: .env
    user: "${AIRFLOW_UID:-1000}:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: "${AIRFLOW__CORE__EXECUTOR}"
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW__CORE__FERNET_KEY}"
      AIRFLOW__CORE__LOAD_EXAMPLES: "${AIRFLOW__CORE__LOAD_EXAMPLES}"
      AIRFLOW__CORE__HOSTNAME_CALLABLE: "socket.gethostname"
      AIRFLOW__CORE__HOSTNAME: "${AIRFLOW__CORE__HOSTNAME}"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}"
      AIRFLOW__CELERY__BROKER_URL: "${AIRFLOW__CELERY__BROKER_URL}"
      AIRFLOW__CELERY__RESULT_BACKEND: "${AIRFLOW__CELERY__RESULT_BACKEND}"
      AIRFLOW__CELERY__WORKER_CONCURRENCY: "${AIRFLOW__CELERY__WORKER_CONCURRENCY}"
      AIRFLOW__API__SECRET_KEY: "${AIRFLOW__API__SECRET_KEY}"
      AIRFLOW__API__AUTH_STRATEGIES: "${AIRFLOW__API__AUTH_STRATEGIES}"
      AIRFLOW__SIMPLE_AUTH_MANAGER__USERNAME: "${AIRFLOW__SIMPLE_AUTH_MANAGER__USERNAME}"
      AIRFLOW__SIMPLE_AUTH_MANAGER__PASSWORD: "${AIRFLOW__SIMPLE_AUTH_MANAGER__PASSWORD}"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    deploy:
      resources:
        limits:
          memory: 1200M
          cpus: "0.75"
        reservations:
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d celery@$${HOSTNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s