version: "3.8"

services:
  worker:
    image: apache/airflow:2.9.2
    command: worker
    env_file: ../.env
    user: "${AIRFLOW_UID:-1000}:0"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d celery@$${HOSTNAME}"]
      interval: 30s
      retries: 5